# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.cache/wt [current_project]
set_property parent.project_path D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.1 [current_project]
set_property ip_output_repo d:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/ALU.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/ALU_control.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/C_U.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/Imm_gen.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/Ins_Mem.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/Jump.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/add_pc.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/data_mem.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/pc_add_2.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/program_counter.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/reg_file.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/special_register.v
  D:/PRJ_TKLL_CPU16bit/PRJ_TKLL_CPU16bit.srcs/sources_1/new/TOP.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top TOP -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
